# Generated by Django 5.1.3 on 2024-11-29 15:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmersMarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('operator', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('zip_code', models.CharField(max_length=10)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('contact_website', models.URLField(blank=True)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_facebook', models.URLField(blank=True)),
                ('contact_instagram', models.CharField(blank=True, max_length=100)),
                ('contact_twitter', models.CharField(blank=True, max_length=100)),
                ('hours_mon', models.CharField(blank=True, max_length=100)),
                ('hours_tue', models.CharField(blank=True, max_length=100)),
                ('hours_wed', models.CharField(blank=True, max_length=100)),
                ('hours_thu', models.CharField(blank=True, max_length=100)),
                ('hours_fri', models.CharField(blank=True, max_length=100)),
                ('hours_sat', models.CharField(blank=True, max_length=100)),
                ('hours_sun', models.CharField(blank=True, max_length=100)),
                ('season_year_round', models.BooleanField(default=False)),
                ('season_opening_month', models.CharField(blank=True, max_length=20)),
                ('season_opening_day', models.IntegerField(blank=True, null=True)),
                ('season_closing_month', models.CharField(blank=True, max_length=20)),
                ('season_closing_day', models.IntegerField(blank=True, null=True)),
                ('accepts_credit', models.BooleanField(default=False)),
                ('accepts_snap', models.BooleanField(default=False)),
                ('accepts_fmnp', models.BooleanField(default=False)),
                ('accepts_philly_food_bucks', models.BooleanField(default=False)),
                ('accepts_cash', models.BooleanField(default=True)),
                ('payment_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_edited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_markets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MarketHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edited_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_snapshot', models.JSONField()),
                ('edited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='markets.farmersmarket')),
            ],
            options={
                'verbose_name_plural': 'Market histories',
                'ordering': ['-edited_at'],
            },
        ),
    ]
