# fly.toml app configuration file generated for market-locator on 2023-12-28T16:36:41-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "market-locator"
primary_region = "ewr"

[build]
dockerfile = "Dockerfile"
# builder = "paketobuildpacks/builder:base"
# buildpacks = ["gcr.io/paketo-buildpacks/go"]

[env]
PORT = "8000"

[http_service]
internal_port = 8000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 1024
